JAVA_CORPUS_TRAIN_NAME = 'train.json'
JAVA_CORPUS_VALID_NAME = 'valid.json'
JAVA_CORPUS_TEST_NAME = 'test.json'

PYTHON_CORPUS_TRAIN_CODE = 'train.code'
PYTHON_CORPUS_VALID_CODE = 'valid.code'
PYTHON_CORPUS_TEST_CODE = 'test.code'

PYTHON_CORPUS_ALL_CODE = 'data_ps.declbodies'
PYTHON_CORPUS_ALL_COMMENT = 'data_ps.descriptions'
PYTHON_CORPUS_TRAIN_COMMENT = 'train.comment'
PYTHON_CORPUS_VALID_COMMENT = 'valid.comment'
PYTHON_CORPUS_TEST_COMMENT = 'test.comment'

PYTHON_CORPUS_TRAIN_KEYWORDS = 'train.keywords'
PYTHON_CORPUS_VALID_KEYWORDS = 'valid.keywords'
PYTHON_CORPUS_TEST_KEYWORDS = 'test.keywords'

CORPUS_TRAIN = 'train'
CORPUS_VALID = 'valid'
CORPUS_TEST = 'test'

EXTENSION_CODE = '.code'
EXTENSION_COMMENT = '.comment'
EXTENSION_JSON = '.json'

DCNL_DCSP = ' DCNL DCSP '
DCNL = ' DCNL '
DCSP = ' DCSP '

CODE = 'Code:'
DESCRIPTION = 'Desc:'

CODE_MIN_JAVA = 5
CODE_MAX_JAVA = 100

DESC_MIN_JAVA = 5
DESC_MAX_JAVA = 20

CODE_MIN_PYTHON = 5
CODE_MAX_PYTHON = 200

DESC_MIN_PYTHON = 5
DESC_MAX_PYTHON = 100
